### ISSUE TITLE
Do you still support the FIM mode?

### ISSUE THREAD

**Issue by yujun-8848** [nlpxucan/WizardLM#112]
i know, starcoder support fim mode, can use vscode generate code , wizardcoder still support the FIM mode?

**Comment by ChiYeungLaw** [comment]
Yes. It still supports fim mode. In our [paper](https://arxiv.org/abs/2306.08568), we also evaluate our model on the DS-1000 insertion tasks. Our model also achieves much better performance than Starcoder.
