### ISSUE TITLE
WizardCoder training datasets have public?

### ISSUE THREAD

**Issue by cdj0311** [nlpxucan/WizardLM#148]
hi，
The papar "WizardCoder: Empowering Code Large Language Models with Evol-Instruct" shows that the training data already public, but I can't found it.
![image](https://github.com/nlpxucan/WizardLM/assets/5728315/9095fb97-dae4-4db3-b0e6-b235bca2ea4d)

**Comment by karrtikiyer** [comment]
I read somewhere in one of their git pages that it is currently under some legal review before they make it public.
