### ISSUE TITLE
Where I can download the math_instruction_data.json?

### ISSUE THREAD

**Issue by w32zhong** [nlpxucan/WizardLM#158]
Without the data math_instruction_data.json, how can I reproduce your evaluation?

**Comment by flyinghpluo** [comment]
Thank you for your interest in our work, our training data is currently not publicly available. If you want to evaluate  the GSM8k or MATH benchmarks, please refer to the ["**Evalution**"](https://github.com/nlpxucan/WizardLM/tree/main/WizardMath#evaluation) section of the WizardMath README.

**Comment by w32zhong** [comment]
Thank you for your response.

I want to evaluate the model, but given that the data is not available, I hope we can know at least on which datasets it is trained, do we need to train it on MATH training set? is it zero-shot? For it to be used in a research evaluation, I think these are important information.

**Comment by flyinghpluo** [comment]
Due to company policies，Our training data is currently not publicly available. You can learn  about in detail how our training data are constructed through our paper [https://arxiv.org/abs/2308.09583](https://arxiv.org/abs/2308.09583)

**Comment by w32zhong** [comment]
Thanks for your notice and sharing your paper. I will close this issue.

**Comment by EmiyaArcher233** [comment]
Hello, when can we get math_instruction_data.json? We want to reproduce your evaluation, but we don't have the necessary data. Could you release the dataset?
