### ISSUE TITLE
Why the model claims it's trained by OpenAI?

### ISSUE THREAD

**Issue by edwardzjl** [nlpxucan/WizardLM#174]
I'm using vicuna's prompt:

```python
"""A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.

{history}
USER: {input}
ASSISTANT:"""
```

When I ask "What date is it today", the model provides the following response:

"As an AI developed by OpenAI, I don't have access to real-time data or personal information including dates or specific times. However, you can easily find today's date on your device or through a quick internet search."

**Comment by teknium1** [comment]
That's because it was trained by OpenAI

**Comment by Symbolk** [comment]
Maybe the reason is that the instruction data is from GPT-3.5/4 from OpenAI?
