### ISSUE TITLE
Missing tokenizer.model for WizardMath-70B-V1.0

### ISSUE THREAD

**Issue by OMGnotThatGuy** [nlpxucan/WizardLM#193]
I was trying to quantize [WizardLM/WizardMath-70B-V1.0](https://huggingface.co/WizardLM/WizardMath-70B-V1.0/tree/main) on Hugging Face, but noticed that the tokenizer.model is missing. Is it possible to update HF repo with the tokenizer.model?

**Comment by flyinghpluo** [comment]
Thank you for your interest in our work.  I have uploaded the tokenizer.model

**Comment by bboshiZ** [comment]
> Thank you for your interest in our work. I have uploaded the tokenizer.model

[WizardMath-7B-V1.0 
](https://huggingface.co/WizardLM/WizardLM-13B-V1.1/tree/main) tokenizer.model is missing too

**Comment by flyinghpluo** [comment]
The tokenizer.model of [WizardMath-7B-V1.0](https://huggingface.co/WizardLM/WizardMath-7B-V1.0/tree/main), [WizardMath-13B-V1.0](https://huggingface.co/WizardLM/WizardMath-13B-V1.0/tree/main), and [WizardMath-70B-V1.0](https://huggingface.co/WizardLM/WizardMath-70B-V1.0/tree/main) have been uploaded.  Thank you for your interest in our work.

**Comment by OMGnotThatGuy** [comment]
Thank you so much for the quick response!
