### ISSUE TITLE
Cannot reproduce  WizardCoder-Python series

### ISSUE THREAD

**Issue by yingfhu** [nlpxucan/WizardLM#196]
We use huggingface `WizardLM/WizardCoder-Python-34B-V1.0` but cannot reproduce metrics on humaneval(55 vs 73) using the prompt by your evaluation script(The low accuracy was caused by AssertionError but not invalid grammar)

However,the `WizardCoder-xB-V1.0` series can achieve relative persuasive results. 

Is there anything different between these two series when evaluating?Thanks.

**Comment by ChiYeungLaw** [comment]
You can follow this (tutorial)[https://github.com/nlpxucan/WizardLM/tree/main/WizardCoder#how-to-reproduce-the-732-pass1-on-humaneval-with-greedy-decoding] to reproduce the performance step-by-step.

**Comment by ChiYeungLaw** [comment]
One important point is that do not use transformers > 4.32.0.

**Comment by ChiYeungLaw** [comment]
> You can follow this [tutorial](https://github.com/nlpxucan/WizardLM/tree/main/WizardCoder#how-to-reproduce-the-732-pass1-on-humaneval-with-greedy-decoding) to reproduce the performance step-by-step. If you follow this, you can 100% get the same score.

@NinedayWang Check this.

**Comment by nicoladainese96** [comment]
Sorry what's the deal with transformers > 4.32.0. I believe that the discrepancy in performance between the WizardCode series based on Starcoder and the one based on LLama comes from how the base model treats padding. Could it be so?
