### ISSUE TITLE
Wizardcoder for code completion? 

### ISSUE THREAD

**Issue by andreapiso** [nlpxucan/WizardLM#72]
First of all, thanks for releasing the model. It is way better than anything else that was available up to this point.

I see the prompt used to get Wizardcoder to answer to instructions. I was wondering,  can unprompted wizardcoder be used for code completion like base starcoder (e.g. if I processed its output to make it compatible with the HF Vscode extension)

Secondly, does it retain the capability of performing fill in the middle like the original starcoder model? If so, are the special tokens needed the same?

**Comment by ChiYeungLaw** [comment]
Unprompted, WizardCoder can be used for code completion, similar to the base Starcoder. It also retains the capability of performing fill-in-the-middle, just like the original Starcoder. However, since WizardCoder is trained with instructions, it is advisable to use the instruction formats.
