### ISSUE TITLE
load mush slower than starcoder 

### ISSUE THREAD

**Issue by Yung-Kai** [nlpxucan/WizardLM#76]
Have someone loaded by 
`AutoModelForCausalLM.from_pretrained(MODEL_PATH, torch_dtype=torch.float16, device_map="auto)`
I have tried load starcoder model with A100-40G with approximately 140s to load
but it took me 600+ s to load wizardcoder
Can someone help ?
Is this matter?  : starcoder is separated in 7 pieces while wizardcode is a large bin file

**Comment by dittops** [comment]
@Yung-Kai Were you able to do the generation? I was facing OOM on A100 80 GB, but starcoder was running at the same time.

**Comment by Yung-Kai** [comment]
@ChiYeungLaw Thanks for your response, Did you manage to load the model in a faster way?
