### ISSUE TITLE
evaluate_functional_correctness ${output_path}.jsonl 得到的pass@k结果全是1

### ISSUE THREAD

**Issue by FastBCSD** [nlpxucan/WizardLM#87]
![image](https://github.com/nlpxucan/WizardLM/assets/50363920/4447c348-46f2-4c52-aca8-71f48b0af386)

**Comment by ChiYeungLaw** [comment]
I think you first need to check whether you have generated the codes correctly. Then check whether you install the humaneval environment correctly. Since your capture only provides limit information, it is hard for me to provide a solution.
